
set number                         " Show line numbers
syntax on                          " Syntax highlighting

set ignorecase                     " Search is case-insensitive
set hlsearch                       " Highlight search matches
set incsearch                      " Highlight first matches of searches while typing

set expandtab                      " Insert spaces instead of tabs
set shiftwidth=5                   " Tab = 5 spaces
set softtabstop=5                  " Tab = 5 spaces
set backspace=indent,eol,start     " Modern backspace behavior

